# Generated by Django 5.1.6 on 2025-06-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_remove_project_images_remove_project_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectvideo',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='image_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.DeleteModel(
            name='ProjectVideo',
        ),
    ]
