# Generated by Django 5.2.3 on 2025-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0009_teammemberrequest_teammemberapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
