# Generated by Django 5.2.3 on 2025-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberapplication',
            name='github_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammemberapplication',
            name='what_you_can_do',
            field=models.TextField(blank=True, null=True),
        ),
    ]
