# Generated by Django 5.2.3 on 2025-06-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0012_teammemberapplication_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hosted_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_urls',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
